apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: kegf4mlml-nodejs 
  janus-idp.io/tekton: kegf4mlml-nodejs
  backstage.io/kubernetes-id: kegf4mlml-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kegf4mlml-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml