apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kegf4mlml-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kegf4mlml-nodejs 
  name: kegf4mlml-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: kegf4mlml-nodejs 
